name: Auto Backport PRs

on:
  pull_request:
    types: [closed]  # Kích hoạt khi PR được đóng (hoặc merge)

jobs:
  backport:
    if: github.event.pull_request.merged == true  # Chỉ thực thi nếu PR đã được merged vào main
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu

    permissions:
      contents: write  # Cấp quyền write cho nội dung (cho phép push mã vào repository)
      pull-requests: write  # Cấp quyền write cho pull requests (cho phép tạo và chỉnh sửa PR)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout mã nguồn từ repository để làm việc

      - name: Set up Git for pushing
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create a new branch from staging
        run: |
          # Fetch latest updates
          git fetch origin
          # Checkout to staging branch
          git checkout staging
          git pull origin staging
          # Create a new branch from staging, using PR number to name the branch
          NEW_BRANCH="backport-to-staging-${{ github.event.pull_request.number }}"
          git checkout -b $NEW_BRANCH
          git push origin $NEW_BRANCH  # Push new branch to remote

      - name: Cherry-pick commits from merged PR to the new branch
        run: |
          # Cherry-pick commits from the merged PR into the new branch
          COMMIT_SHA="${{ github.event.pull_request.merge_commit_sha }}"
          git cherry-pick $COMMIT_SHA  # Apply commit from PR to the new branch
          git push origin $NEW_BRANCH  # Push the changes to the new branch

      - name: Create a Pull Request to staging
        run: |
          # Create PR to staging from the newly created branch
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"title": "Backport PR #${{ github.event.pull_request.number }} to staging", "head": "$NEW_BRANCH", "base": "staging"}' \
            https://api.github.com/repos/${{ github.repository }}/pulls
