name: Auto Backport PRs

on:
  pull_request:
    types: [closed]  # Kích hoạt khi PR được đóng (hoặc merge)

jobs:
  backport:
    if: github.event.pull_request.merged == true  # Chỉ thực thi nếu PR đã được merged vào main
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu

    permissions:
      contents: write  # Cấp quyền write cho nội dung (cho phép push mã vào repository)
      pull-requests: write  # Cấp quyền write cho pull requests (cho phép tạo và chỉnh sửa PR)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git for pushing
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Create a new branch from staging
        run: |
          # Fetch latest changes from remote
          git fetch origin
          git checkout staging  # Checkout nhánh staging từ remote
          git pull origin staging  # Đồng bộ nhánh staging với remote
          NEW_BRANCH="backport-to-staging-${{ github.event.pull_request.number }}"
          git checkout -b $NEW_BRANCH  # Tạo nhánh mới từ staging
          git push --set-upstream origin $NEW_BRANCH  # Đặt upstream cho nhánh và push lên remote

      - name: Cherry-pick commits from merged PR with 'theirs' strategy
        run: |
          COMMIT_SHA="${{ github.event.pull_request.merge_commit_sha }}"
          git cherry-pick -X theirs $COMMIT_SHA  # Tự động giữ thay đổi từ `main` khi có xung đột
          git push origin $NEW_BRANCH  # Push các thay đổi vào nhánh con

      - name: Push the branch with upstream
        run: |
          # Đảm bảo upstream branch được thiết lập cho nhánh con và push
          git push --set-upstream origin $NEW_BRANCH  # Thiết lập upstream branch và push lên remote

      - name: Create a Pull Request to staging
        run: |
          curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"title": "Backport PR #${{ github.event.pull_request.number }} to staging", "head": "$NEW_BRANCH", "base": "staging"}' \
            https://api.github.com/repos/${{ github.repository }}/pulls
