name: Auto Backport PRs

on:
  pull_request:
    types: [closed]

jobs:
  backport:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Run backport action
        uses: sorenlouv/backport-github-action@v9.5.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
	  auto_backport_label_prefix: "backport-to:"
          auto_merge: false
          auto_assign: true
          auto_label: true
