name: Auto Backport PRs

on:
  pull_request:
    types: [closed]  # Kích hoạt khi PR được đóng (hoặc merge)

jobs:
  backport:
    if: github.event.pull_request.merged == true  # Chỉ thực thi nếu PR đã được merged
    runs-on: ubuntu-latest  # Chạy trên môi trường Ubuntu

    permissions:
      contents: write  # Cấp quyền write cho nội dung (cho phép push mã vào repository)
      pull-requests: write  # Cấp quyền write cho pull requests (cho phép tạo và chỉnh sửa PR)

    steps:
      - name: Checkout code
        uses: actions/checkout@v2  # Checkout mã nguồn từ repository để làm việc

      - name: Run backport action
        uses: sorenlouv/backport-github-action@v9.5.1  # Sử dụng backport action
        with:
          github_token: ${{ secrets.MY_GITHUB_PAT }}  # Sử dụng Personal Access Token (PAT)
          auto_backport_label_prefix: "backport-to:"  # Tiền tố label (ví dụ: "backport-to:staging")
          auto_merge: false  # Không tự động merge PR
          auto_assign: true  # Tự động assign reviewer
          auto_label: true  # Tự động thêm label vào PR
